### ISSUE TITLE
Compile fails with custom settings

### ISSUE THREAD

**Issue by ronoverdrive** [lordbean-git/reshade-shaders#1]
Like the topic says with at least version 3.4.5 it fails to compile if the custom options are chosen.

**Comment by lordbean-git** [comment]
If v3.4.6 displays the same behavior can you please post the ReShade log. It might not though, I discovered two global defines that still matched normal SMAA ones and renamed them in 3.4.6.

**Comment by lordbean-git** [comment]
I was able to duplicate the problem and have managed to resolve it, which is now available (v3.4.7).
